### PR TITLE
Fix Android login tab

### PR DESCRIPTION
**Pull request by idanstark42**
After talking to Alan he told me about this bug.
This is not the perfect solution, as described [here](https://github.com/expo/expo/issues/8072), but it is the best balance between solving the issue and not changing too much and taking the risk at this late time.

**Don't merge before approval from Alan / Yosi / Dana.**

### CODE REVIEW

**Review by ofekashery — CHANGES_REQUESTED** [review]
Unfortunately, it's still doesn't solve the issue, after clicking on the app icon it opens the app's login screen and not the Chrome Custom Tab of the SSO.

**Comment by idanstark42** [comment]
This is a fix for andoird. I do not have the testing platform for iOS, so you'll have to make that fix.

**Comment by ofekashery** [comment]
@idanstark42 I know, I tested it on Android

**Comment by idanstark42** [comment]
That's wierd... It worked for me... Can you test again (I will also)?

**Pull request closed without merging**
